from .routes import (
    admin_ai,
    admin_database,
    admin_notifications,
    admin_dashboard,
    auth,
    analytics,
    dev_tasks,
    invites,
    moderation,
    notifications,
    organizations,
    posts,
    products,
    reviews,
    subscriptions,
    qr,
    social,
)  # noqa: F401

